name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Frontend
        working-directory: frontend
        env:
          REACT_APP_API_URL: http://${{ secrets.EC2_HOST }}:8000
          CI: false
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/smart-society
            git pull origin main
            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
            echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env
            docker compose down
            docker compose build frontend --build-arg REACT_APP_API_URL=http://${{ secrets.EC2_HOST }}:8000
            export GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
            export EC2_HOST=${{ secrets.EC2_HOST }}
            docker compose up -d
            echo "Deployed successfully"